// biome-ignore-all format: tests are intentionally compact evidence fixtures
// biome-ignore-all assist/source/organizeImports: test imports are intentionally compact

import{describe,expect,it}from"vitest";import{checkoutExperienceGraph,checkoutExperienceGraphJson,deserializeExperienceGraph,replayTransitions,serializeExperienceGraph,validateExperienceGraph}from"../src";
describe("Experience Graph",()=>{
 it("validates checkout branching",()=>{const r=validateExperienceGraph(checkoutExperienceGraph);expect(r.valid).toBe(true);expect(r.reachableScreenIds).toEqual(["screen.cart","screen.checkout","screen.error","screen.processing","screen.product","screen.success"])});
 it("serializes deterministically and round-trips",()=>{const shuffled={...checkoutExperienceGraph,transitions:[...checkoutExperienceGraph.transitions].reverse()};expect(serializeExperienceGraph(checkoutExperienceGraph)).toBe(serializeExperienceGraph(shuffled));expect(deserializeExperienceGraph(checkoutExperienceGraphJson)).toEqual(checkoutExperienceGraph)});
 it("replays success",()=>{const r=replayTransitions(checkoutExperienceGraph,"start.product",[{type:"click"},{type:"click"},{type:"submit"},{type:"condition",expression:"payment.status === 'success'"}]);expect(r.finalDestination).toEqual({screenId:"screen.success"});expect(r.steps.map(x=>x.transitionId)).toEqual(["product.add-to-cart","cart.checkout","checkout.submit","processing.success"])});
 it("rejects missing destinations and reports orphan/unreachable screens",()=>{const invalid={...checkoutExperienceGraph,flows:[{...checkoutExperienceGraph.flows[0],screenIds:[...checkoutExperienceGraph.flows[0].screenIds,"screen.orphan"]}],transitions:[...checkoutExperienceGraph.transitions,{...checkoutExperienceGraph.transitions[0],id:"duplicate.semantic"},{...checkoutExperienceGraph.transitions[1],id:"missing.destination",action:{type:"navigate" as const,destination:{screenId:"screen.missing"}}}]};const r=validateExperienceGraph(invalid);expect(r.valid).toBe(false);expect(r.issues.map(x=>x.code)).toEqual(expect.arrayContaining(["CONFLICTING_TRANSITION","MISSING_DESTINATION","ORPHAN_SCREEN","UNREACHABLE_SCREEN"]))});
 it("represents overlay, back, scroll and state-change",()=>{const g={...checkoutExperienceGraph,transitions:[...checkoutExperienceGraph.transitions,{id:"checkout.help",source:{screenId:"screen.checkout",nodeId:"checkout.help"},trigger:{type:"click" as const},action:{type:"overlay" as const,destination:{screenId:"screen.checkout",nodeId:"checkout.help-dialog"}}},{id:"checkout.help.back",source:{screenId:"screen.checkout",nodeId:"checkout.help-dialog"},trigger:{type:"keyboard" as const},action:{type:"back" as const}},{id:"checkout.scroll",source:{screenId:"screen.checkout"},trigger:{type:"click" as const},action:{type:"scroll" as const,targetNodeId:"checkout.summary"}},{id:"checkout.state",source:{screenId:"screen.checkout"},trigger:{type:"click" as const},action:{type:"state-change" as const,state:"couponOpen",value:true}}]};expect(g.transitions.map(x=>x.action.type)).toEqual(expect.arrayContaining(["overlay","back","scroll","state-change"]))});
});
