// biome-ignore-all format: semantic registry implementation is maintained as a stable contract\nimport type { ComponentDefinition, ComponentRegistry } from "./types";

const decision = (use: string, avoid: string, graph: string) => ({
  whenToUse: [use],
  whenNotToUse: [avoid],
  contextFit: ["Dashboard", "Form", "Application shell"],
  alternatives: [
    "Use the semantically adjacent registered component when the context differs.",
  ],
  composition: {
    allowedChildren: ["text", "icon", "custom"],
    preferredParents: ["section", "card", "form", "list-item"],
    nestingRules: ["Do not nest the same interactive component inside itself."],
  },
  antiPatterns: [
    "Choosing this component from appearance alone.",
    "Duplicating the semantic component under another name.",
  ],
  responsiveBehavior: [
    "Preserve accessible target size.",
    "Reflow content before truncating semantic content.",
  ],
  experienceGraphImplications: [graph],
});

const make = (
  id: string,
  name: string,
  description: string,
  semanticType: string,
  bindingId: string,
  role: string,
  namePolicy: "required" | "recommended" | "inherited",
  use: string,
  avoid: string,
  graph: string,
  variants: string[] = ["default"],
  states: string[] = ["default"],
  tokens: string[] = ["color.foreground", "color.surface"],
): ComponentDefinition => ({
  id,
  version: 1,
  name,
  description,
  anatomy: [
    { id: "content", description: "Semantic component content", required: true },
    { id: "actions", description: "Optional contextual actions" },
  ],
  variants: variants.map((variant) => ({
    id: variant,
    description: `${variant} variant.`,
  })),
  states: states.map((state) => ({
    id: state,
    description: `${state} state.`,
    interactive: ["default", "hover", "focus", "selected"].includes(state),
  })),
  tokens,
  accessibility: {
    role,
    accessibleName: namePolicy,
    keyboard: ["Tab"],
    focusable: [
      "button",
      "textbox",
      "dialog",
      "tablist",
      "navigation",
    ].includes(role),
    requirements: [
      "Do not rely on color alone for meaning.",
      "Preserve semantic labels and roles.",
    ],
  },
  decision: decision(use, avoid, graph),
  renderer: { bindingId, semanticType },
  codeMapping: { strategy: "project-mapping", componentName: name },
});

const definitions: ComponentDefinition[] = [
  make(
    "uiforge.button",
    "Button",
    "Invokes an action or submits a form.",
    "button",
    "button",
    "button",
    "required",
    "Use for an intentional action.",
    "Do not use for navigation when a link is correct.",
    "Click/submit may create a graph transition.",
    ["primary", "secondary", "destructive", "ghost"],
    ["default", "hover", "focus", "disabled", "loading"],
    ["color.primary", "color.onPrimary", "control.radius"],
  ),
  make(
    "uiforge.input",
    "Input",
    "Collects one scalar user value.",
    "input",
    "input",
    "textbox",
    "required",
    "Use for a single scalar value.",
    "Do not use for long-form content.",
    "Input/change may participate in a graph transition.",
    ["default", "search"],
    ["default", "focus", "disabled", "invalid"],
  ),
  make(
    "uiforge.label",
    "Label",
    "Names an associated form control.",
    "text",
    "label",
    "label",
    "inherited",
    "Use to name a form control.",
    "Do not use as a generic heading.",
    "No navigation semantics.",
    ["default"],
    ["default"],
    ["color.foreground", "text.body"],
  ),
  make(
    "uiforge.card",
    "Card",
    "Groups related information.",
    "card",
    "card",
    "region",
    "recommended",
    "Use to group related information or controls.",
    "Do not use as decoration around every element.",
    "Interactive cards expose trigger and destination through the graph.",
    ["default", "interactive"],
    ["default", "selected"],
    ["color.surface", "color.border", "control.radius", "shadow.subtle"],
  ),
  make(
    "uiforge.badge",
    "Badge",
    "Shows compact status or category metadata.",
    "text",
    "badge",
    "status",
    "inherited",
    "Use for short status or category metadata.",
    "Do not use as a primary action.",
    "Usually no graph transition unless explicitly interactive.",
    ["default", "success", "warning", "error"],
  ),
  make(
    "uiforge.avatar",
    "Avatar",
    "Represents a person or entity.",
    "image",
    "avatar",
    "img",
    "required",
    "Use for identity representation.",
    "Do not use as a generic decorative icon.",
    "No transition unless explicitly interactive.",
    ["default"],
    ["default"],
    ["control.radius"],
  ),
  make(
    "uiforge.alert",
    "Alert",
    "Communicates important contextual feedback.",
    "text",
    "alert",
    "alert",
    "inherited",
    "Use for important contextual feedback.",
    "Do not use for every informational sentence.",
    "Feedback state does not imply navigation.",
    ["info", "success", "warning", "error"],
  ),
  make(
    "uiforge.dialog",
    "Dialog",
    "Temporarily interrupts context with focused content.",
    "dialog-trigger",
    "dialog",
    "dialog",
    "required",
    "Use for focused tasks that remain in the current context.",
    "Do not use for ordinary page content.",
    "Open/close is a local state; actions may create graph transitions.",
    ["default", "confirmation"],
    ["closed", "open"],
    ["color.surface", "control.radius", "shadow.medium"],
  ),
  make(
    "uiforge.tabs",
    "Tabs",
    "Switches between peer views in one context.",
    "custom",
    "tabs",
    "tablist",
    "required",
    "Use for a small set of peer views.",
    "Do not use for independent destinations.",
    "Tab changes are state transitions, not necessarily new screens.",
    ["default"],
    ["default", "disabled"],
  ),
  make(
    "uiforge.table",
    "Table",
    "Presents comparable structured records.",
    "table",
    "table",
    "table",
    "required",
    "Use when records are compared across stable columns.",
    "Do not use for simple key/value summaries.",
    "Row actions may navigate to detail or edit screens.",
    ["default", "compact"],
    ["default", "loading", "empty"],
  ),
  make(
    "uiforge.list",
    "List",
    "Presents a repeated collection of related items.",
    "list",
    "list",
    "list",
    "recommended",
    "Use for repeated peer items.",
    "Do not use when column comparison is primary.",
    "Interactive items may emit click/keyboard transitions.",
    ["default", "interactive"],
    ["default", "empty"],
  ),
  make(
    "uiforge.navigation",
    "Navigation",
    "Links between product destinations.",
    "custom",
    "navigation",
    "navigation",
    "required",
    "Use for navigational destinations.",
    "Do not use for actions that do not change location.",
    "Each destination maps to a graph navigation transition.",
  ),
  make(
    "uiforge.sidebar",
    "Sidebar",
    "Persistent or collapsible application navigation.",
    "custom",
    "sidebar",
    "navigation",
    "required",
    "Use for persistent product-level navigation.",
    "Do not use for short transient lists.",
    "Navigation links transition through the graph; collapse is local state.",
    ["expanded", "collapsed"],
    ["expanded", "collapsed"],
  ),
  make(
    "uiforge.header",
    "Header",
    "Provides page or application context.",
    "custom",
    "header",
    "banner",
    "recommended",
    "Use to establish page or application context.",
    "Do not use as a generic container.",
    "Header actions may emit graph transitions.",
    ["page", "application"],
  ),
  make(
    "uiforge.form",
    "Form",
    "Groups controls for a related submission.",
    "custom",
    "form",
    "form",
    "recommended",
    "Use when controls participate in one task.",
    "Do not use for one unrelated input.",
    "Submit may create a graph transition after validation.",
    ["default", "compact"],
    ["default", "submitting", "invalid"],
  ),
  make(
    "uiforge.empty-state",
    "EmptyState",
    "Explains why a collection is empty and offers a next step.",
    "custom",
    "empty-state",
    "status",
    "inherited",
    "Use when an expected collection has no content.",
    "Do not use for loading or error states.",
    "Optional action may transition to create/import/search.",
    ["default", "search"],
  ),
];

export const componentRegistry: ComponentRegistry = {
  version: "uiforge.components/v1",
  components: Object.fromEntries(definitions.map((item) => [item.id, item])),
};
