import type { TokenSet } from "./types.js";

export const defaultTokenSet: TokenSet = {
  version: "uiforge.tokens/v1",
  primitives: {
    "color.blue.600": {
      name: "color.blue.600",
      kind: "color",
      value: "#2563eb",
    },
    "color.gray.50": { name: "color.gray.50", kind: "color", value: "#f9fafb" },
    "color.gray.100": {
      name: "color.gray.100",
      kind: "color",
      value: "#f3f4f6",
    },
    "color.gray.500": {
      name: "color.gray.500",
      kind: "color",
      value: "#6b7280",
    },
    "color.gray.700": {
      name: "color.gray.700",
      kind: "color",
      value: "#374151",
    },
    "color.gray.900": {
      name: "color.gray.900",
      kind: "color",
      value: "#111827",
    },
    "color.white": { name: "color.white", kind: "color", value: "#ffffff" },
    "color.green.600": {
      name: "color.green.600",
      kind: "color",
      value: "#16a34a",
    },
    "color.amber.600": {
      name: "color.amber.600",
      kind: "color",
      value: "#d97706",
    },
    "color.red.600": { name: "color.red.600", kind: "color", value: "#dc2626" },
    "space.1": { name: "space.1", kind: "spacing", value: "4px" },
    "space.2": { name: "space.2", kind: "spacing", value: "8px" },
    "space.3": { name: "space.3", kind: "spacing", value: "12px" },
    "space.4": { name: "space.4", kind: "spacing", value: "16px" },
    "space.5": { name: "space.5", kind: "spacing", value: "20px" },
    "space.6": { name: "space.6", kind: "spacing", value: "24px" },
    "space.8": { name: "space.8", kind: "spacing", value: "32px" },
    "space.10": { name: "space.10", kind: "spacing", value: "40px" },
    "space.12": { name: "space.12", kind: "spacing", value: "48px" },
    "space.16": { name: "space.16", kind: "spacing", value: "64px" },
    "font.family.sans": {
      name: "font.family.sans",
      kind: "typography",
      value: "Inter, ui-sans-serif, system-ui, sans-serif",
    },
    "font.size.body": {
      name: "font.size.body",
      kind: "typography",
      value: "14px",
    },
    "font.size.body-lg": {
      name: "font.size.body-lg",
      kind: "typography",
      value: "16px",
    },
    "font.size.title": {
      name: "font.size.title",
      kind: "typography",
      value: "32px",
    },
    "font.size.metric": {
      name: "font.size.metric",
      kind: "typography",
      value: "28px",
    },
    "radius.sm": { name: "radius.sm", kind: "radius", value: "6px" },
    "radius.md": { name: "radius.md", kind: "radius", value: "8px" },
    "radius.lg": { name: "radius.lg", kind: "radius", value: "12px" },
    "radius.xl": { name: "radius.xl", kind: "radius", value: "16px" },
    "shadow.subtle": {
      name: "shadow.subtle",
      kind: "shadow",
      value: "0 1px 2px rgb(0 0 0 / 0.06)",
    },
    "shadow.medium": {
      name: "shadow.medium",
      kind: "shadow",
      value: "0 4px 12px rgb(0 0 0 / 0.10)",
    },
    "border.default": { name: "border.default", kind: "border", value: "1px" },
    "breakpoint.sm": {
      name: "breakpoint.sm",
      kind: "breakpoint",
      value: "640px",
    },
    "breakpoint.md": {
      name: "breakpoint.md",
      kind: "breakpoint",
      value: "768px",
    },
    "breakpoint.lg": {
      name: "breakpoint.lg",
      kind: "breakpoint",
      value: "1024px",
    },
    "breakpoint.xl": {
      name: "breakpoint.xl",
      kind: "breakpoint",
      value: "1280px",
    },
    "motion.fast": { name: "motion.fast", kind: "motion", value: "120ms" },
    "motion.normal": { name: "motion.normal", kind: "motion", value: "200ms" },
  },
  semantic: {
    "color.background": {
      name: "color.background",
      kind: "color",
      value: "{color.white}",
      semanticRole: "background",
      primitiveRef: "color.white",
    },
    "color.surface": {
      name: "color.surface",
      kind: "color",
      value: "{color.white}",
      semanticRole: "surface",
      primitiveRef: "color.white",
    },
    "color.foreground": {
      name: "color.foreground",
      kind: "color",
      value: "{color.gray.900}",
      semanticRole: "foreground",
      primitiveRef: "color.gray.900",
    },
    "color.mutedForeground": {
      name: "color.mutedForeground",
      kind: "color",
      value: "{color.gray.500}",
      semanticRole: "mutedForeground",
      primitiveRef: "color.gray.500",
    },
    "color.border": {
      name: "color.border",
      kind: "color",
      value: "{color.gray.100}",
      semanticRole: "border",
      primitiveRef: "color.gray.100",
    },
    "color.primary": {
      name: "color.primary",
      kind: "color",
      value: "{color.blue.600}",
      semanticRole: "primary",
      primitiveRef: "color.blue.600",
    },
    "color.success": {
      name: "color.success",
      kind: "color",
      value: "{color.green.600}",
      semanticRole: "success",
      primitiveRef: "color.green.600",
    },
    "color.warning": {
      name: "color.warning",
      kind: "color",
      value: "{color.amber.600}",
      semanticRole: "warning",
      primitiveRef: "color.amber.600",
    },
    "color.error": {
      name: "color.error",
      kind: "color",
      value: "{color.red.600}",
      semanticRole: "error",
      primitiveRef: "color.red.600",
    },
    "color.onPrimary": {
      name: "color.onPrimary",
      kind: "color",
      value: "{color.white}",
      semanticRole: "onPrimary",
      primitiveRef: "color.white",
    },
    "text.body": {
      name: "text.body",
      kind: "typography",
      value: "{font.size.body}",
    },
    "text.body-lg": {
      name: "text.body-lg",
      kind: "typography",
      value: "{font.size.body-lg}",
    },
    "text.title": {
      name: "text.title",
      kind: "typography",
      value: "{font.size.title}",
    },
    "text.metric": {
      name: "text.metric",
      kind: "typography",
      value: "{font.size.metric}",
    },
    "layout.pageGap": {
      name: "layout.pageGap",
      kind: "spacing",
      value: "{space.6}",
    },
    "layout.sectionGap": {
      name: "layout.sectionGap",
      kind: "spacing",
      value: "{space.4}",
    },
    "control.radius": {
      name: "control.radius",
      kind: "radius",
      value: "{radius.md}",
    }
  },
  rawValueExceptions: []
};
