// biome-ignore-all format: semantic contract is intentionally compact
export const COLOR_STRATEGY_VERSION="uiforge.color-strategy/v1" as const;
export type ColorRole={name:string;light:string;dark:string;description:string};
export type ColorStrategy={version:typeof COLOR_STRATEGY_VERSION;primary:string;secondary:string;accent?:string;roles:ColorRole[];tonalScales:Record<string,Record<string,string>>;chart:string[];provenance:{source:string;designStrategyVersion:string};validation:string[]};
function hex(h:string){const n=h.replace("#","");const v=n.length===3?n.split("").map(x=>x+x).join(""):n;return [0,2,4].map(i=>parseInt(v.slice(i,i+2),16)/255).map(x=>x ?? 0)}
function lin(v:number){return v<=.03928?v/12.92:((v+.055)/1.055) ** 2.4}
export function luminance(h:string){const [r,g,b]=hex(h).map(lin);return .2126*(r ?? 0)+.7152*(g ?? 0)+.0722*(b ?? 0)}
export function contrast(a:string,b:string){const l1=luminance(a),l2=luminance(b);return (Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05)}
function mix(a:string,b:string,t:number){const A=hex(a),B=hex(b);return `#${A.map((x,i)=>Math.round((x+((B[i] ?? 0)-x)*t)*255).toString(16).padStart(2,"0")).join("")}`
export function buildColorStrategy(input:{primary:string;secondary:string;accent?:string;domain:string;designStrategyVersion:string}):ColorStrategy{
 const white="#ffffff",black="#111111", scale=(seed:string)=>({100:mix(white,seed,.08),200:mix(white,seed,.16),300:mix(white,seed,.28),400:mix(white,seed,.45),500:seed,600:mix(seed,black,.12),700:mix(seed,black,.28),800:mix(seed,black,.45),900:mix(seed,black,.65)});
 const roles:ColorRole[]=[{name:"primary",light:input.primary,dark:mix(input.primary,white,.18),description:"primary brand anchor"},{name:"secondary",light:input.secondary,dark:mix(input.secondary,white,.18),description:"secondary brand anchor"},{name:"surface",light:"#ffffff",dark:"#171717",description:"large content surface"},{name:"foreground",light:"#111111",dark:"#f5f5f5",description:"primary text"},{name:"border",light:"#d4d4d4",dark:"#404040",description:"component boundary"},{name:"success",light:"#15803d",dark:"#4ade80",description:"success status"},{name:"warning",light:"#a16207",dark:"#facc15",description:"warning status"},{name:"error",light:"#b91c1c",dark:"#f87171",description:"error status"},{name:"info",light:"#0369a1",dark:"#38bdf8",description:"informational status"}];
 if(input.accent) roles.push({name:"accent",light:input.accent,dark:mix(input.accent,white,.18),description:"optional purposeful accent"});
 const validation=validateColorStrategy({version:COLOR_STRATEGY_VERSION,primary:input.primary,secondary:input.secondary,accent:input.accent,roles,tonalScales:{primary:scale(input.primary),secondary:scale(input.secondary)},chart:["#2563eb","#16a34a","#ca8a04","#dc2626","#9333ea"],provenance:{source:input.domain,designStrategyVersion:input.designStrategyVersion},validation:[]});
 return {...validation.length?{...({} as ColorStrategy),validation}:({} as ColorStrategy),version:COLOR_STRATEGY_VERSION,primary:input.primary,secondary:input.secondary,accent:input.accent,roles,tonalScales:{primary:scale(input.primary),secondary:scale(input.secondary)},chart:["#2563eb","#16a34a","#ca8a04","#dc2626","#9333ea"],provenance:{source:input.domain,designStrategyVersion:input.designStrategyVersion},validation};
}
export function validateColorStrategy(s:ColorStrategy):string[]{const e:string[]=[];if(!s.primary||!s.secondary)e.push("MISSING_BRAND_ANCHOR");if(s.accent&&!s.roles.some(r=>r.name==="accent"))e.push("INVALID_ACCENT_ROLE");const fg=s.roles.find(r=>r.name==="foreground")?.light,surface=s.roles.find(r=>r.name==="surface")?.light;if(fg&&surface&&contrast(fg,surface)<4.5)e.push("INSUFFICIENT_TEXT_CONTRAST");if(new Set(s.roles.map(r=>r.name)).size!==s.roles.length)e.push("DUPLICATE_ROLE");return e}
export function deterministicColorHash(s:ColorStrategy){return JSON.stringify(s)}
