// biome-ignore-all format: semantic contract is kept compact for review
export const DESIGN_SKILL_VERSION="uiforge.design-skill/v1" as const;
export const DESIGN_STRATEGY_VERSION="uiforge.design-strategy/v1" as const;
export type ProductIntent={domain:string;productType:string;primaryTasks:string[];platforms:("web"|"mobile")[]};
export type Skill={id:string;version:1;family:string;domains:string[];patterns:string[];constraints:string[];antiPatterns:string[]};
export type SkillMatch={skillId:string;matched:string[];reasons:string[]};
export type DesignStrategy={version:typeof DESIGN_STRATEGY_VERSION;product:{domain:string;productType:string};skills:string[];informationArchitecture:string[];navigation:string;tasks:string[];screenArchetypes:string[];componentPatterns:string[];interaction:string[];responsive:string[];accessibility:string[];antiPatterns:string[];provenance:SkillMatch[]};
export const skills:readonly Skill[]=[{id:"dashboard",version:1,family:"dashboard",domains:["analytics","finance","saas"],patterns:["summary","trend","comparison"],constraints:["clear hierarchy"],antiPatterns:["card spam"]},{id:"data-management",version:1,family:"crud",domains:["finance","saas","operations"],patterns:["table","filter","search"],constraints:["stable columns"],antiPatterns:["unstructured records"]},{id:"quick-entry",version:1,family:"form",domains:["finance","commerce","productivity"],patterns:["quick-entry","inline validation"],constraints:["minimal fields"],antiPatterns:["long form for simple tasks"]},{id:"personal-finance",version:1,family:"finance",domains:["finance"],patterns:["transaction","budget","category","spending"],constraints:["money precision"],antiPatterns:["ambiguous amounts"]},{id:"ecommerce-browse",version:1,family:"ecommerce",domains:["ecommerce"],patterns:["catalog","product detail","cart","checkout"],constraints:["clear purchase path"],antiPatterns:["hidden price"]},{id:"responsive-navigation",version:1,family:"responsive",domains:["*"],patterns:["sidebar","bottom navigation","adaptive layout"],constraints:["mobile reflow"],antiPatterns:["desktop shrink-only"]},{id:"accessibility",version:1,family:"accessibility",domains:["*"],patterns:["semantic labels","keyboard","contrast"],constraints:["WCAG-aware"],antiPatterns:["color-only meaning"]}];
export function discoverSkills(intent:ProductIntent):SkillMatch[]{const d=intent.domain.toLowerCase();return skills.map(s=>{const domain=s.domains.includes("*")||s.domains.includes(d)||s.domains.includes(intent.productType.toLowerCase());const task=s.patterns.filter(p=>intent.primaryTasks.some(t=>t.toLowerCase().includes(p.split(" ")[0] ?? p)));return {skillId:s.id,matched:domain?[s.family,...task]:task,reasons:domain?[`domain:${d}`,...task.map(x=>`task:${x}`)]:task.map(x=>`task:${x}`)}}).filter(x=>x.matched.length)}
export function composeStrategy(i:ProductIntent):DesignStrategy{const p=discoverSkills(i),ids=[...new Set(p.map(x=>x.skillId))],s=skills.filter(x=>ids.includes(x.id));return {version:DESIGN_STRATEGY_VERSION,product:{domain:i.domain,productType:i.productType},skills:ids,informationArchitecture:["overview","primary-task","records","settings"],navigation:i.platforms.includes("mobile")&&!i.platforms.includes("web")?"bottom-navigation":"adaptive-sidebar-or-tabs",tasks:i.primaryTasks,screenArchetypes:[i.domain==="finance"?"dashboard":"overview",...i.primaryTasks],componentPatterns:[...new Set(s.flatMap(x=>x.patterns))],interaction:["explicit actions","inline validation"],responsive:[...new Set(s.flatMap(x=>x.constraints))],accessibility:s.find(x=>x.id==="accessibility")?.constraints??[],antiPatterns:[...new Set(s.flatMap(x=>x.antiPatterns))],provenance:p}}
export function validateStrategy(s:DesignStrategy):string[]{const e:string[]=[];if(s.version!==DESIGN_STRATEGY_VERSION)e.push("INVALID_VERSION");if(s.skills.some(id=>!skills.some(x=>x.id===id)))e.push("UNKNOWN_SKILL");if(!s.skills.length)e.push("NO_SKILLS");if(new Set(s.skills).size!==s.skills.length)e.push("DUPLICATE_SKILL");return e}

export * from "./visual-design";
