"use client";

import { useState } from "react";

const CODE_FILES = [
  {
    name: "page.tsx",
    path: "apps/web/src/app/dashboard/page.tsx",
    language: "tsx",
    content: `// Generated by UIForge Codegen v1
// Target: React 19 + Next.js App Router + Tailwind CSS v4 + shadcn/ui

import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import Link from "next/link";

export default function DashboardPage() {
  return (
    <main className="min-h-screen bg-slate-950 p-8 text-white">
      <div className="mx-auto max-w-5xl space-y-6">
        <header className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div>
            <h1 className="text-2xl font-bold tracking-tight">Overview</h1>
            <p className="text-sm text-slate-400">FinTech Analytics & KPIs</p>
          </div>
          <Link href="/mobile-list">
            <Button variant="default" className="bg-cyan-500 text-slate-950 hover:bg-cyan-400">
              Open Details →
            </Button>
          </Link>
        </header>

        <section className="grid gap-4 md:grid-cols-3">
          <Card className="border-slate-800 bg-slate-900/60 text-white">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium text-slate-400">Total Revenue</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-cyan-400">$39.6K</div>
              <p className="text-xs text-emerald-400 mt-1">+6.2% vs last month</p>
            </CardContent>
          </Card>
        </section>
      </div>
    </main>
  );
}`,
  },
  {
    name: "tokens.css",
    path: "packages/design-tokens/src/theme.css",
    language: "css",
    content: `@theme {
  --color-primary-base: #06b6d4;
  --color-primary-hover: #22d3ee;
  --color-surface-base: #020617;
  --color-surface-subtle: #0f172a;
  --color-border-subtle: #1e293b;

  --spacing-gap-default: 1rem; /* space.4 */
  --spacing-padding-default: 1rem;
  --radius-md: 0.5rem; /* 8px */
}`,
  },
  {
    name: "mcp-agent-prompt.md",
    path: "docs/mcp/agent-instructions.md",
    language: "markdown",
    content: `## Agent Bridge via Model Context Protocol

To query this screen directly in Cursor / Claude / Windsurf:
\`\`\`bash
# Endpoint:
http://127.0.0.1:3100/mcp

# Tool:
get_screen(projectId: "sample-project", screenId: "screen.dashboard")
\`\`\`

Returns canonical UI Schema with zero visual hallucination.`,
  },
];

export default function CodeSpecView() {
  const [activeFileIndex, setActiveFileIndex] = useState(0);
  const [copied, setCopied] = useState(false);

  const activeFile = CODE_FILES[activeFileIndex] ??
    CODE_FILES[0] ?? {
      name: "page.tsx",
      path: "apps/web/src/app/dashboard/page.tsx",
      language: "tsx",
      content: "",
    };

  const handleCopy = () => {
    navigator.clipboard.writeText(activeFile.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex h-full w-full flex-col overflow-hidden bg-slate-950 text-slate-100">
      {/* File Tabs */}
      <div className="flex items-center justify-between border-b border-slate-800 bg-slate-900/60 px-4 py-2">
        <div className="flex items-center gap-2">
          {CODE_FILES.map((file, idx) => (
            <button
              key={file.path}
              type="button"
              onClick={() => setActiveFileIndex(idx)}
              className={`rounded-md px-3 py-1 text-xs font-mono transition-colors ${
                activeFileIndex === idx
                  ? "bg-slate-800 text-cyan-400 font-semibold"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              {file.name}
            </button>
          ))}
        </div>

        <button
          type="button"
          onClick={handleCopy}
          className="rounded-md bg-cyan-600 px-3 py-1 text-xs font-semibold text-slate-950 hover:bg-cyan-500"
        >
          {copied ? "Copied!" : "Copy File"}
        </button>
      </div>

      <div className="border-b border-slate-800/80 bg-slate-950 px-4 py-1.5 font-mono text-[11px] text-slate-500">
        {activeFile.path}
      </div>

      {/* Code Editor Preview */}
      <div className="flex-1 overflow-auto p-4 font-mono text-xs leading-relaxed">
        <pre className="text-slate-300">
          <code>{activeFile.content}</code>
        </pre>
      </div>
    </div>
  );
}
